name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install --global @microsoft/rush
      - run: rush change -v
      - run: rush install
      - run: rush build --verbose
